env:
  global:
    - CI_BUILD=true
    - PYTHONPATH="/home/travis/build/engelmav/smartesl/api"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - postgresql
language: python
python:
  - "3.6"
install:
  - pip install -r api/requirements.txt

script:
  - pytest
